language: python

sudo: false
fast_finish: true

python:
  - "3.4"
  - "3.5"

install:
  - pip install coveralls
  - pip install -r requirements.txt
  - pip install .

script:
  - coverage run setup.py test
  # - nosetests

after_success:
  - coveralls

branches:
  only:
    - master